### ISSUE TITLE
error: Justfile does not contain recipe `k8s-dev-tools`.

### ISSUE THREAD

**Issue by neitsab** [ublue-os/bluefin-docs#21]
Question on: https://github.com/ublue-os/bluefin/tree/master/_docs/bluefin-dx.md

Following the docs to [install k8s](https://docs.projectbluefin.io/bluefin-dx#kubernetes-and-other-cloud-native-tooling) results in an error:

```
~% ujust k8s-dev-tools
error: Justfile does not contain recipe `k8s-dev-tools`.
```

Checking `ujust --choose` for "kubernetes" or "k8s" does not return anything.

I'm on an up-to-date bluefin-dx:stable (40.20240820.0), checked the forum and the main repo but no reference to this.

I'll leave up to you whether to implement it or to remove it from the docs :smile: 

Thanks for all your work!

**Comment by neitsab** [comment]
PS: it appears kind is installed (from `bluefin-cli` maybe?), but not the others (kubectl, k9s...)

**Comment by neitsab** [comment]
Sorry, just saw that this was quite new and that there was an issue already opened to implement what's documented: https://github.com/ublue-os/config/issues/308

Feel free to close!

**Comment by castrojo** [comment]
Let's leave this open until that merges, when I wrote it up I thought it'd be merged faster, heh.

**Comment by neitsab** [comment]
No problem! Meanwhile I tried to run  `brew bundle --file /usr/share/ublue-os/homebrew/kubernetes.Brewfile` (from https://github.com/ublue-os/config/pull/309/files) but it failed with

    Error: Read-only file system @ rb_sysopen - /usr/share/ublue-os/homebrew/kubernetes.Brewfile.lock.json

**Comment by castrojo** [comment]
Maybe try copying it over to your home directory first.

**Comment by castrojo** [comment]
This just landed and should be in the next set of builds, thanks!

**Comment by neitsab** [comment]
Awesome, great job and thank you! 🙏🏻
