### ISSUE TITLE
Question: rpm-ostree is documented as deprecated; how to add kargs with bootc?

### ISSUE THREAD

**Issue by klmcwhirter** [ublue-os/bluefin-docs#55]
From the standpoint of a potentially new bluefin user, how should `rpm-ostree kargs` be accomplished with bootc?

*Note the [Day-0 Planning playbook section](https://docs.projectbluefin.io/introduction#day-0-planning) describes rpm-ostree as deprecated and will be removed in Spring 2025. I am trying to decide when to install bluefin on my "production" laptop.*

Note I am not talking about in a container, but on metal. *I am currently running bluefin in a VM and am unable to test my exact use case - see below.*

The `bootc` docs describe what to do in a container - [add files at `/usr/lib/bootc/kargs.d`](https://containers.github.io/bootc/building/kernel-arguments.html) but it seems that location should be read-only on a metal install. *Note a quick test shows that it currently is. I tried to touch a file in that dir and got an error that it is a read-only fs.*

Thanks.

#### Use case:
I need to add `acpi_backlight=native` to cause screen brightness control to work with my laptop - Acer Nitro 5.

With Fedora WS I modify the `/etc/default/grub` file to make the settings changes I need. And then execute `sudo grub2-mkconfig -o /boot/grub2/grub.cfg`.

In the current state of bluefin, it looks like I will use `rpm-ostree kargs --append=acpi_backlight=native` which will create a new deployment. That is exactly what I want. 

I am also assuming that because it modifies the "default" deployment that all future deployments will inherit that setting. Although that is not clear in the [Core OS doc page](https://docs.fedoraproject.org/en-US/fedora-coreos/kernel-args/) either.

**Comment by castrojo** [comment]
> In the current state of bluefin, it looks like I will use rpm-ostree kargs --append=acpi_backlight=native which will create a new deployment. That is exactly what I want.

Yeah this is what you want, it'll add the command to the right place and it will keep the setting through upgrades.

**Comment by klmcwhirter** [comment]
Thanks for the quick response.

But what is going to be the procedure when `rpm-ostree` is removed?

The answer to that question may cause me to delay my install until Summer '25 at least.

Are better tooling in progress to replace the kargs and other grub settings? I saw reference to a yaml file for things like timeout, etc. That works, but is not great. I would prefer to handle all of those config item in one ostree deployment.

All this stuff is making me question when/if to make the leap.

Thanks again for the help.

**Comment by castrojo** [comment]
I think I'll move the kernel arg section to the administrator's guide to clarify.

**Comment by klmcwhirter** [comment]
Thanks please let me know when that is up. Not urgent - prioritize as you need to. I probably will not move until after the new year. I need a stable laptop right now ;)

**Comment by castrojo** [comment]
> The answer to that question may cause me to delay my install until Summer '25 at least.

We're not going to remove anything that removes karg functionality, we'll use whatever the replacement is, but according to the rhel docs it looks like they're going with rpm-ostree for now.

**Comment by klmcwhirter** [comment]
BTW, your YT channel videos have been a huge help to short-circuit the learning curve. FYI

**Comment by klmcwhirter** [comment]
I was able to successfully use `rpm-ostree kargs --append=acpi_backlight=native` to stage a deploy that added the kargs specified.

As long as that capability does not go away when rpm-ostree is removed I am in a good spot.

As such, I am closing this issue. No doc changes needed.
